### PR TITLE
update pulsarDistances

### PR DESCRIPTION
**Pull request by paulthebaker**
- include all 37 NANOGrav pulsars in pulsarDistances.txt
- remove non-NANOGrav pulsars (12!)
- add pulsarDistances.info: contains source/method for data

### CODE REVIEW

**Comment by stevertaylor** [comment]
Why is this removing non-NANOGrav pulsars? NX01 (including this distance file) is for use with all PTA data and not just NANOGrav. Or is this commit maintaining all existing pulsar names but just switching over their distance estimates to NANOGrav estimates?

**Comment by paulthebaker** [comment]
I wasn't sure what you wanted.  I should have guessed... I'll put them back in.  There are 49 pulsars in the most recent IPTA data.  I'll double check and make sure all are in there (presumably, the 12 I cut are all we need).

**Comment by stevertaylor** [comment]
Awesome, thank you! Sorry for not clarifying earlier.

**Comment by paulthebaker** [comment]
Latest commit:
- include all 49 IPTA pulsars
- update all distances from most recent citation I could find
- prefer parallax to DM
- use NE2001 for all DM

**Pull request merged**
